version: "3"

services:
  # Database
  db_second:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpstarter
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db_second
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_second
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpstarter
  # Wordpress
  wordpress:
    depends_on:
      - db_second
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes: ["./:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db_second:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpstarter
networks:
  wpstarter:
volumes:
  db_data:
